<?php

namespace Database\Seeders;

use App\Models\ArtistRegistration;
use Illuminate\Database\Seeder;

class ArtistSeedDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeds = [
            [
                'registration_id' => 'FOLK-VOCAL-RAJ-5678',
                'full_name' => 'Rameshwar Lal Sharma',
                'father_husband_name' => 'Ramswaroop Sharma',
                'dob' => '1988-06-15',
                'age' => 38,
                'gender' => 'Male',
                'mobile' => '9876543210',
                'email' => 'rameshwar.folk@example.com',
                'address' => 'House No 42, Gram Post Samod, Tehsil Chomu',
                'district' => 'Jaipur',
                'state' => 'Rajasthan',
                'pincode' => '303806',
                'category' => 'lok',
                'discipline' => 'gayan',
                'art_description' => 'पारंपरिक राजस्थानी मांगणियार एवं मांड लोक गायन के वरिष्ठ कलाकार।',
                'experience' => '16 Years',
                'aadhaar_number' => '9845 1234 5678',
                'aadhaar_name' => 'Rameshwar Lal Sharma',
                'passbook_name' => 'Rameshwar Lal Sharma',
                'photo_path' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
                'video_path' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'pan_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_front_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_back_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'passbook_path' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
                'youtube' => 'https://youtube.com/@rameshwar_folk_art',
                'instagram' => 'https://instagram.com/rameshwar_artist',
                'facebook' => 'https://facebook.com/rameshwarfolk',
                'portfolio' => 'https://rameshwarfolkart.in',
                'status' => 'APPROVED',
                'status_text_hi' => 'स्वीकृत (Approved)',
                'status_text_en' => 'Verified & Approved',
            ],
            [
                'registration_id' => 'TRIBAL-DANCE-MP-6789',
                'full_name' => 'Sunita Bai Maravi',
                'father_husband_name' => 'Mangal Singh Maravi',
                'dob' => '1994-11-20',
                'age' => 31,
                'gender' => 'Female',
                'mobile' => '8765432109',
                'email' => 'sunita.gond@example.com',
                'address' => 'Village Patangarh, Dindori Block',
                'district' => 'Dindori',
                'state' => 'Madhya Pradesh',
                'pincode' => '481880',
                'category' => 'janjatiya',
                'discipline' => 'nritya',
                'art_description' => 'गोंड जनजातीय पारंपरिक कर्मा एवं सैला लोक नृत्य कलाकार।',
                'experience' => '12 Years',
                'aadhaar_number' => '7890 2345 6789',
                'aadhaar_name' => 'Sunita Bai Maravi',
                'passbook_name' => 'Sunita Bai Maravi',
                'photo_path' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
                'video_path' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'pan_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_front_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_back_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'passbook_path' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
                'youtube' => 'https://youtube.com/@gond_tribal_dance',
                'instagram' => 'https://instagram.com/sunita_tribal_art',
                'facebook' => '',
                'portfolio' => '',
                'status' => 'UNDER_REVIEW',
                'status_text_hi' => 'सत्यापन हेतु प्रस्तुत (Submitted for Verification)',
                'status_text_en' => 'Under Review by Directorate of Culture',
            ],
            [
                'registration_id' => 'FOLK-DANCE-PUN-1234',
                'full_name' => 'Gurpreet Singh Dhillon',
                'father_husband_name' => 'Sardar Balwant Singh',
                'dob' => '1991-07-22',
                'age' => 35,
                'gender' => 'Male',
                'mobile' => '9872013456',
                'email' => 'gurpreet.bhangra@example.com',
                'address' => 'VPO Jandiala Guru, Majha Region',
                'district' => 'Amritsar',
                'state' => 'Punjab',
                'pincode' => '143115',
                'category' => 'lok',
                'discipline' => 'nritya',
                'art_description' => 'पारंपरिक पंजाबी भांगड़ा, झूमर एवं मालवई गिद्दा के प्रमुख नर्तक।',
                'experience' => '13 Years',
                'aadhaar_number' => '6543 9876 1234',
                'aadhaar_name' => 'Gurpreet Singh Dhillon',
                'passbook_name' => 'Gurpreet Singh Dhillon',
                'photo_path' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
                'video_path' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'pan_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_front_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_back_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'passbook_path' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
                'youtube' => 'https://youtube.com/@gurpreet_bhangra_punjab',
                'instagram' => 'https://instagram.com/dhillon_bhangra_live',
                'facebook' => 'https://facebook.com/gurpreetbhangra',
                'portfolio' => '',
                'status' => 'APPROVED',
                'status_text_hi' => 'स्वीकृत (Approved)',
                'status_text_en' => 'Verified & Approved',
            ],
            [
                'registration_id' => 'CLASSICAL-DANCE-TAM-0987',
                'full_name' => 'Meenakshi Sundaram Iyer',
                'father_husband_name' => 'K. S. Sundaram Iyer',
                'dob' => '1995-02-14',
                'age' => 31,
                'gender' => 'Female',
                'mobile' => '9444018293',
                'email' => 'meenakshi.dance@example.com',
                'address' => 'No 18, Sannathi Street, Mylapore',
                'district' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600004',
                'category' => 'shastriya',
                'discipline' => 'nritya',
                'art_description' => 'तंजावुर शैली में शास्त्रीय भरतनाट्यम नृत्य की ख्यातिप्राप्त गुरु।',
                'experience' => '17 Years',
                'aadhaar_number' => '8765 4321 0987',
                'aadhaar_name' => 'Meenakshi Sundaram Iyer',
                'passbook_name' => 'Meenakshi Sundaram Iyer',
                'photo_path' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
                'video_path' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'pan_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_front_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_back_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'passbook_path' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
                'youtube' => 'https://youtube.com/@meenakshi_bharatanatyam',
                'instagram' => 'https://instagram.com/meenakshi_dance_arts',
                'facebook' => '',
                'portfolio' => 'https://meenakshisundaram.art',
                'status' => 'APPROVED',
                'status_text_hi' => 'स्वीकृत (Approved)',
                'status_text_en' => 'Verified & Approved',
            ],
            [
                'registration_id' => 'FOLK-VOCAL-BIH-7654',
                'full_name' => 'Shanti Devi Jha',
                'father_husband_name' => 'Baidyanath Jha',
                'dob' => '1985-05-18',
                'age' => 41,
                'gender' => 'Female',
                'mobile' => '9771029485',
                'email' => 'shanti.mithila@example.com',
                'address' => 'Village Ranti, Post Madhubani',
                'district' => 'Madhubani',
                'state' => 'Bihar',
                'pincode' => '847211',
                'category' => 'lok',
                'discipline' => 'gayan',
                'art_description' => 'पारंपरिक मैथिली सोहर, कजरी एवं झूमर लोकगीत गायन कलाकार।',
                'experience' => '20 Years',
                'aadhaar_number' => '5432 1098 7654',
                'aadhaar_name' => 'Shanti Devi Jha',
                'passbook_name' => 'Shanti Devi Jha',
                'photo_path' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
                'video_path' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
                'pan_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_front_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'aadhaar_back_path' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
                'passbook_path' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
                'youtube' => '',
                'instagram' => 'https://instagram.com/mithila_heritage_art',
                'facebook' => 'https://facebook.com/shantidevimadhubani',
                'portfolio' => '',
                'status' => 'UNDER_REVIEW',
                'status_text_hi' => 'सत्यापन हेतु प्रस्तुत (Submitted for Verification)',
                'status_text_en' => 'Under Review by Directorate of Culture',
            ],
        ];

        foreach ($seeds as $data) {
            ArtistRegistration::updateOrCreate(
                ['registration_id' => $data['registration_id']],
                $data
            );
        }
    }
}
